import { Role } from "../../common/constants/roles.js";

export type ResourceConfig = {
  key: string;
  label: string;
  model: string;
  module: string;
  minReadRole: Role;
  minWriteRole: Role;
  searchableFields: string[];
  defaultSort: string;
  softDelete: boolean;
};

export const RESOURCE_REGISTRY: Record<string, ResourceConfig> = {
  products: {
    key: "products",
    label: "Products",
    model: "product",
    module: "products",
    minReadRole: Role.CUSTOMER,
    minWriteRole: Role.ADMIN,
    searchableFields: ["name", "code", "productType", "description"],
    defaultSort: "createdAt",
    softDelete: true,
  },
  categories: {
    key: "categories",
    label: "Categories",
    model: "productCategory",
    module: "categories",
    minReadRole: Role.CUSTOMER,
    minWriteRole: Role.ADMIN,
    searchableFields: ["name", "slug", "description"],
    defaultSort: "sortOrder",
    softDelete: true,
  },
  inventory: {
    key: "inventory",
    label: "Inventory",
    model: "inventoryItem",
    module: "inventory",
    minReadRole: Role.MANAGER,
    minWriteRole: Role.ADMIN,
    searchableFields: ["sku", "warehouseName", "status"],
    defaultSort: "updatedAt",
    softDelete: true,
  },
  carts: {
    key: "carts",
    label: "Carts",
    model: "cart",
    module: "cart",
    minReadRole: Role.CUSTOMER,
    minWriteRole: Role.CUSTOMER,
    searchableFields: ["status"],
    defaultSort: "updatedAt",
    softDelete: true,
  },
  wishlists: {
    key: "wishlists",
    label: "Wishlists",
    model: "wishlistItem",
    module: "wishlist",
    minReadRole: Role.CUSTOMER,
    minWriteRole: Role.CUSTOMER,
    searchableFields: [],
    defaultSort: "createdAt",
    softDelete: true,
  },
  orders: {
    key: "orders",
    label: "Orders",
    model: "order",
    module: "orders",
    minReadRole: Role.CUSTOMER,
    minWriteRole: Role.MANAGER,
    searchableFields: ["orderNumber", "status"],
    defaultSort: "createdAt",
    softDelete: true,
  },
  payments: {
    key: "payments",
    label: "Payments",
    model: "payment",
    module: "payments",
    minReadRole: Role.MANAGER,
    minWriteRole: Role.ADMIN,
    searchableFields: ["gateway", "paymentMethod", "status", "transactionId"],
    defaultSort: "createdAt",
    softDelete: true,
  },
  refunds: {
    key: "refunds",
    label: "Refunds",
    model: "refundRequest",
    module: "payments",
    minReadRole: Role.SUPPORT,
    minWriteRole: Role.ADMIN,
    searchableFields: ["status", "reason"],
    defaultSort: "createdAt",
    softDelete: true,
  },
  coupons: {
    key: "coupons",
    label: "Coupons",
    model: "coupon",
    module: "coupons",
    minReadRole: Role.MANAGER,
    minWriteRole: Role.ADMIN,
    searchableFields: ["code", "title", "description", "status"],
    defaultSort: "createdAt",
    softDelete: true,
  },
  notifications: {
    key: "notifications",
    label: "Notifications",
    model: "notification",
    module: "notifications",
    minReadRole: Role.SUPPORT,
    minWriteRole: Role.ADMIN,
    searchableFields: ["type", "title", "body", "status"],
    defaultSort: "createdAt",
    softDelete: true,
  },
  delivery: {
    key: "delivery",
    label: "Delivery Assignments",
    model: "deliveryAssignment",
    module: "delivery",
    minReadRole: Role.DELIVERY_PARTNER,
    minWriteRole: Role.MANAGER,
    searchableFields: ["status", "notes"],
    defaultSort: "assignedAt",
    softDelete: true,
  },
  tracking: {
    key: "tracking",
    label: "Tracking Logs",
    model: "trackingLog",
    module: "tracking",
    minReadRole: Role.DELIVERY_PARTNER,
    minWriteRole: Role.DELIVERY_PARTNER,
    searchableFields: ["status", "message"],
    defaultSort: "createdAt",
    softDelete: false,
  },
  support: {
    key: "support",
    label: "Support Tickets",
    model: "supportTicket",
    module: "support",
    minReadRole: Role.SUPPORT,
    minWriteRole: Role.SUPPORT,
    searchableFields: ["subject", "category", "priority", "status", "message"],
    defaultSort: "createdAt",
    softDelete: true,
  },
  analytics: {
    key: "analytics",
    label: "User Activity",
    model: "userActivity",
    module: "analytics",
    minReadRole: Role.MANAGER,
    minWriteRole: Role.ADMIN,
    searchableFields: ["action", "module"],
    defaultSort: "createdAt",
    softDelete: false,
  },
  reports: {
    key: "reports",
    label: "Sales Reports",
    model: "salesReport",
    module: "reports",
    minReadRole: Role.MANAGER,
    minWriteRole: Role.ADMIN,
    searchableFields: [],
    defaultSort: "periodStart",
    softDelete: false,
  },
  settings: {
    key: "settings",
    label: "Settings",
    model: "appSetting",
    module: "settings",
    minReadRole: Role.ADMIN,
    minWriteRole: Role.SUPER_ADMIN,
    searchableFields: ["key", "group", "label"],
    defaultSort: "group",
    softDelete: false,
  },
  banners: {
    key: "banners",
    label: "Banners",
    model: "banner",
    module: "marketing",
    minReadRole: Role.MANAGER,
    minWriteRole: Role.ADMIN,
    searchableFields: ["title", "placement"],
    defaultSort: "createdAt",
    softDelete: true,
  },
};

export const RESOURCE_KEYS = Object.keys(RESOURCE_REGISTRY);
